In [1]:
from cleaning import Cleaning
import pandas as pd
import numpy as np
import sklearn

# importation des donnees

In [2]:
data_frame=pd.read_csv('../dataset/archive/spam_ham_dataset.csv')
data_frame.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [3]:
data_frame=data_frame.drop(columns=['Unnamed: 0','label_num'])
data_frame.head()

label                                               text
0   ham  Subject: enron methanol ; meter # : 988291\r\n...
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...
3  spam  Subject: photoshop , windows , office . cheap ...
4   ham  Subject: re : indian springs\r\nthis deal is t...

In [4]:
data=data_frame.values
data.shape

(5171, 2)

### Dovision de donnees en 2 partie: labele et les emails

In [7]:
labels=data[:,:1]
data=data[:,1:]

# Pre-traitement

In [10]:
cl=Cleaning(data)

[nltk_data] Downloading package punkt to
[nltk_data]     /home/elkharroubi/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/elkharroubi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [11]:
data[0][0]

"Subject: enron methanol ; meter # : 988291\r\nthis is a follow up to the note i gave you on monday , 4 / 3 / 00 { preliminary\r\nflow data provided by daren } .\r\nplease override pop ' s daily volume { presently zero } to reflect daily\r\nactivity you can obtain from gas control .\r\nthis change is needed asap for economics purposes ."

In [19]:
labels[:6]

array([['ham'],
       ['ham'],
       ['ham'],
       ['spam'],
       ['ham'],
       ['ham']], dtype=object)

In [12]:
data=cl.processing()

# Post processing

In [17]:
from sklearn import preprocessing

#### Label encoding

In [20]:
le = preprocessing.LabelEncoder()
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
labels.reshape(-1)

array(['ham', 'ham', 'ham', ..., 'ham', 'ham', 'spam'], dtype=object)

In [25]:
le=le.fit(labels)
labels=le.transform(labels.reshape(-1))

/home/elkharroubi/.local/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/elkharroubi/.local/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [27]:
labels

array([0, 0, 0, ..., 0, 0, 1])

## TF-IDF

In [32]:
vectorizer = TfidfVectorizer()
# reshape sert a convertir la taille de de notre donnees de 2D a une seule dimension
X = vectorizer.fit_transform(data.reshape(-1))


array(['aa', 'aaa', 'aabda', ..., 'zzocb', 'zzso', 'zzsyt'], dtype=object)

In [40]:
vectorizer.get_feature_names_out().shape

(37845,)

In [51]:
X.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Classification

### Arabre de decision

In [44]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
# pour diviser notre dara en 2 partie (entrainment et le test)
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,labels,test_size=0.3)

In [52]:
clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [53]:
clf.score(x_train,y_train)

1.0

In [67]:
x_test.toarray()[1]

array([0., 0., 0., ..., 0., 0., 0.])

In [68]:
y_test

0

In [59]:
from sklearn.metrics import accuracy_score
y_predict=clf.predict(x_test)

In [79]:

print(accuracy_score(y_test,y_predict))

0.9304123711340206


### SVM

In [84]:
def x(a=10):
    return 2*a

In [80]:
from sklearn import svm
# support vector machine
clf = svm.SVC() # Linear Kernel
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [83]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9819587628865979


# naive bayes classifier

# Reduction de dimensions 

# Fine-tuning des parametres